version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: odinsdb
      POSTGRES_USER: odins
      POSTGRES_PASSWORD: odins
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - DATABASE_URL=postgres://odins:odins@db:5432/odinsdb
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
