# Render.com Blueprint
# Automatically deploy to Render with one click
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: odins-almanac-server
    env: node
    region: oregon
    plan: starter
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: APP_BASE_URL
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_STARTER_PRICE_ID
        sync: false
      - key: STRIPE_PRO_PRICE_ID
        sync: false
      - key: STRIPE_PLATINUM_PRICE_ID
        sync: false
      - key: STRIPE_ENTERPRISE_PRICE_ID
        sync: false
    autoDeploy: true
