name: Deploy Odinsalmanac server to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install server deps
        working-directory: server
        run: npm ci || npm install

      - name: Zip server for deployment
        run: |
          cd server
          zip -r ../release.zip .
          cd ..
          ls -la release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8877547382D3441199425E8535F73C2C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_006B6A88688E4509A0557C8D2EE08A51 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9C9543B6F195411CA49F8D1E7139BF22 }}

      # Deploy to Azure Web App production slot
      # The slot-name: 'production' parameter ensures deployment goes to the main app
      # and not to a deployment slot (which would fail with 404 if the slot doesn't exist)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          package: release.zip
